FROM node:latest
WORKDIR usr/src/app
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 3000
CMD ["npm", "start"]

version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb


Cd nodeserver/

npm init

Then display package.json

Edit the file 
In test coma 
" start" : "node index.js"
In same directory create index.js file 

Console.log("hello ");

Then run using
npm start 

Then go to Chrome 
And type node http server listen on any ip address  
Then copy and paste in index.js file 
And run 
npm start 

Then type command 
npm install --save-exact 
It's automatically created package lock json file